[package]
name = "rustkb-index"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
model2vec-rs = { version = "0.3.0", optional = true, default-features = false, features = ["hf-hub", "fancy-regex"] }
rustkb-core.workspace = true
semver = "1.0.28"
serde = "1.0.229"
serde_json = "1.0.151"
tantivy = "0.26.2"
thiserror = "2.0.21"
tracing = "0.1.44"

[lints]
workspace = true

[features]
semantic = ["dep:model2vec-rs"]
